[project]
name = "django-react-todo"
version = "0.1.0"
description = "Todo アプリケーションのバックエンド"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
    "djangorestframework>=3.15.2",
    "django-rest-knox>=5.0.2",
    "autopep8>=2.3.1",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
]

[tool.uv.sources]
